### PR TITLE
Multiple cleanup items for TO_LAB

### LINKED ISSUE #15: Update to use OSAL socket API
Is your feature request related to a problem? Please describe.
Currently uses cFE supplied network_includes.h and not the abstracted OSAL calls

Describe the solution you'd like
Update to use OSAL

Describe alternatives you've considered
None

Additional context
See osapi-os-net.h and/or OSAL API.

Requester Info
Jacob Hageman - NASA/GSFC

### LINKED ISSUE #22: TO_LAB should better follow cmd/tlm patterns in other modules
**Is your feature request related to a problem? Please describe.**
The TO_LAB implementation currently does not adhere to the command/telemetry processing patterns established in CFE core and other modules.

**Describe the solution you'd like**
- Each command handler should be its own function with its own distinct structure type that is passed in to it
- Housekeeping should put its payload into a separate sub-structure called "Payload"
- Telemetry/Command naming conventions documented in CFE should be adhered to

**Additional context**
Part of the reason for some of these patterns is they help future-proof the code and also help avoid issues like #21.

**Requester Info**
Joseph Hickey, Vantage Systems Inc.

### LINKED ISSUE #23: TO_LAB should put all global variables into a global structure
**Is your feature request related to a problem? Please describe.**
TO_LAB has several "bare" global variables, which are not namespace-qualified.  These should all be put into a global structure, similar to the way other modules isolate their global varables.

**Describe the solution you'd like**
Implement a `TO_LAB_Global` data structure to isolate these values from the global namespace.

**Additional context**
Note that global variables in shared objects are by default put into a "common" section which can have weird effects on namespace clashes.  This is why it is important to put them into a struct (which in this case is basically a namespace isolation mechanism).

**Requester Info**
Joseph Hickey, Vantage Systems Inc.

### PR DESCRIPTION
**Pull request by jphickey**
**Describe the contribution**
Cleans up multiple aspects of the TO_LAB implementation. Details Below.

Fixes #15
Fixes #22
Fixes #23

These change sets are submitted as a single pull request, as they have inter-dependencies between them and will trigger conflicts if presented individually. This pull request still contains each fix as an individual commit, so each one can be independently reviewed.

For #15 / commit 17180f06: Change TO_LAB to use the OSAL socket API rather than calling BSD sockets functions directly.

For #23 / commit d041045: This creates a TO_LAB_Global namespace to isolate these global variables from other modules and prevent collision

For #22 / commit a66df71: Follow the naming conventions in the CFE naming convention document and follow message processing patterns from other modules

**Testing performed**
Build for native for both debug/release builds, with unit tests enabled. Confirmed normal operation of TO_LAB using the Python cFS_GroundSystem tool to enable telemetry output and verify that telemetry is being received as normal.

**Expected behavior changes**
No impact to behavior.

**System(s) tested on**
Ubuntu 18.04 LTS, 64 bit

**Contributor Info - All information REQUIRED for consideration of pull request**
Joseph Hickey, Vantage Systems, Inc.

### CODE REVIEW

**Comment by jphickey** [comment]
Note This pull request is also likely to fix #21 as well (need to test separately)

**Comment by jphickey** [comment]
Confirmed this fixes #21 - to_lab builds cleanly on Raspberry Pi.

**Comment by jphickey** [comment]
NOTE: rebased to updated master (2020226 baseline) and resolved conflicts.

**Comment by astrogeco** [comment]
CCB Fast Tracked - Reviewed by J. Hageman

**Pull request merged**
