### PR TITLE
Fix #30, Resolve doxygen warning

### LINKED ISSUE #30: Fix doxygen warnings
**Describe the bug**
Doxygen warnings are generated when building the documentation

**To Reproduce**
1. From cFS/ do `make doc`
2. Observe the warnings generated in `cFS/build/doc/warnings.log`

**Expected behavior**
No warnings should be generated

**Reporter Info**
Leor Bleier, GSFC\582

### PR DESCRIPTION
**Pull request by lbleier-GSFC**
**Describe the contribution**
Fix #30 
Resolve doxygen warnings

**Testing performed**
Steps taken to test the contribution:

1. Corrected line(s) that generated warnings
2. Rebuilt documentation with `make doc`
3. Observed no warnings generated
4. Viewed relevant page(s) to verify correctness

**Expected behavior changes**
Changes to documentation only; no code impact

**Contributor Info - All information REQUIRED for consideration of pull request**
Leor Bleier, NASA\GSFC

### CODE REVIEW

**Comment by skliper** [comment]
> Header files aren't supposed to instantiate data, just define it. (isn't this a standards issue?)

Yes, standards issue and a new ticket, see #32.  Just fix the path in this one.

**Comment by skliper** [comment]
@lbleier-GSFC can you fix per @jphickey comment?

**Comment by lbleier-GSFC** [comment]
Done

**Comment by astrogeco** [comment]
@lbleier-GSFC can you update the issue name as "Fix #NUMBER," need the "#" for github to link the issue and we've been using commas as a separator.

**Comment by lbleier-GSFC** [comment]
@astrogeco Is that better?

**Comment by skliper** [comment]
autolink still missing, and preferred commit message: "Fix #30, Resolve doxygen warning"

**Comment by skliper** [comment]
Fixed the issue link and updated title, not sure why it wouldn't autolink... did it by hand.

**Comment by astrogeco** [comment]
CCB 2020-04-29 : APPROVED

**Pull request merged**
